#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# for ubunut based distos only
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -;
apt update;
sudo apt install nodejs;
npm install --g npx;
